version: '3.4'

services:
  employee-app:
    image: employees
    container_name: employees.app
    build:
      context: .
      dockerfile: Dockerfile-employees
    depends_on:
      - employees-db

  employees-db:
    image: mysql:latest
    container_name: employees.db
    environment:
      - MYSQL_ROOT_PASSWORD=Password
      - MYSQL_DATABASE=employeesDb
    ports:
      - 5001:3306